#!/usr/bin/env bash
#
# one_click_install.sh — Pantheon Mini V8.11
#
# Workspace + V7 baseline validators + V8.5–V8.11 ports adapted to Mini's
# Active Mini 7-agent operating team. Uses ~/.hermes-mini-<slug>/ namespace so it
# coexists with a full Pantheon install (~/.hermes-<slug>/) on the same
# host.
#
# Flags:
#   bash scripts/one_click_install.sh                       # interactive
#   bash scripts/one_click_install.sh --validate-only       # validators only
#   bash scripts/one_click_install.sh --no-bootstrap        # skip 7 per-agent homes
#   bash scripts/one_click_install.sh --no-dreaming         # skip nightly Dreaming cron
#   bash scripts/one_click_install.sh --skip-adapter-install
#   bash scripts/one_click_install.sh --setup-keys          # interactive secure API key setup
#   bash scripts/one_click_install.sh -y                    # non-interactive, apply everything

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MODE_VALIDATE_ONLY=0
SKIP_BOOTSTRAP=0
SKIP_DREAMING=0
SKIP_ADAPTER_INSTALL=0
SETUP_KEYS=0
ASSUME_YES=0

for arg in "$@"; do
    case "$arg" in
        --validate-only)        MODE_VALIDATE_ONLY=1 ;;
        --no-bootstrap)         SKIP_BOOTSTRAP=1 ;;
        --no-dreaming)          SKIP_DREAMING=1 ;;
        --skip-adapter-install) SKIP_ADAPTER_INSTALL=1 ;;
        --setup-keys)           SETUP_KEYS=1 ;;
        -y|--yes)               ASSUME_YES=1 ;;
        -h|--help) sed -n '3,18p' "$0"; exit 0 ;;
    esac
done

echo "==================================================================="
echo " Pantheon Mini V8.11 — Full Installer"
echo "==================================================================="
echo " Paperclip = company/control plane"
echo " Hermes    = per-agent harness (7 ~/.hermes-mini-<slug>/ homes)"
echo " Adapter   = hermes_local (npm: hermes-paperclip-adapter)"
echo " Arthur    = Project Manager / Head (openai/gpt-5-mini)"
echo " Namespace = ~/.hermes-mini-*  (coexists with full Pantheon)"
echo "==================================================================="
echo

# Step 1: workspace
echo "==> Step 1/8: Create workspace directories"
mkdir -p \
    workspace/01_PRDs workspace/02_SDDs workspace/03_Feature_Tickets \
    workspace/04_TDD_Red_Tests workspace/05_QA_Audit_Logs \
    workspace/06_Project_Repos workspace/07_Finalization workspace/wiki

if [ ! -f "workspace/MASTER_STATUS.md" ]; then
    cp templates/MASTER_STATUS.template.md workspace/MASTER_STATUS.md 2>/dev/null || cat > workspace/MASTER_STATUS.md <<'EOT'
# MASTER_STATUS

## Active Projects

| Project | Domain | Stage | Active Ticket | Owner | Attempt | Status | Last Updated |
|---|---|---|---|---|---:|---|---|

## Project Registry

_No active projects yet._
EOT
fi
echo "  workspace ready"
echo

# Step 2: V7 validators + V8.6-V8.11 patch validators
echo "==> Step 2/8: Run validators"
python3 scripts/validate.py
echo

if [ "$MODE_VALIDATE_ONLY" = "1" ]; then
    echo "Validate-only mode. Exiting."
    exit 0
fi

# Step 3-4: mini doesn't ship an agentcompanies/v1 converter
echo "==> Step 3/8: (mini skips agentcompanies/v1 conversion — V7 baseline kept)"
echo

# Step 5: bootstrap 7 per-agent Hermes homes (V8.5 -> V8.11, adapted to mini namespace)
if [ "$SKIP_BOOTSTRAP" = "0" ]; then
    echo "==> Step 5/8: Bootstrap 7 per-agent Hermes homes (Active Mini operating team) (~/.hermes-mini-<slug>)"
    python3 - <<'PYEOF'
import json, pathlib, textwrap
HOME = pathlib.Path.home()
agents = json.load(open("SoftwareHouse/paperclip/agents.json"))["agents"]
# V8.11: bootstrap only the 7-agent Active Mini operating team.
# Each active agent carries an `active_mini_role` field (set in agents.json).
created = 0
for a in agents:
    if not a.get("active_mini_role"):
        continue
    if not a.get("model"):
        continue
    slug = (a.get("name","unknown")).lower()
    home = HOME / f".hermes-mini-{slug}"
    home.mkdir(exist_ok=True)
    for sub in ("cron","logs","skills","sessions","memories"):
        (home / sub).mkdir(exist_ok=True)
    cfg = home / "config.yaml"
    if not cfg.exists():
        cfg.write_text(textwrap.dedent(f"""\
            # Generated by Pantheon Mini V8.11 bootstrap (Active Mini operating team)
            # Agent: {slug} ({a['name']})
            model:
              name: {a['model']}
            toolsets:
              enabled: [terminal, file, web, code_execution, mcp]
            ui:
              banner: false
            memory:
              enabled: true
            skills:
              local_dir: skills
            """))
    soul = home / "SOUL.md"
    if not soul.exists():
        soul.write_text(f"# SOUL\n\n## Identity\n\n# {a['name']} — {a.get('role','?')}\n\n## Role\n\n{a.get('description','')}\n")
    mem = home / "MEMORY.md"
    if not mem.exists():
        mem.write_text(f"# MEMORY\n\nAgent slug: {slug}\nCanonical id: {a['id']}\nRole: {a.get('role','?')}\nModel: {a.get('model')}\n")
    usr = home / "USER.md"
    if not usr.exists():
        usr.write_text("# USER\n\nMain contact: Arthur — Project Manager (Pantheon Mini)\n")
    created += 1
print(f"bootstrap: {created} mini homes created/updated under ~/.hermes-mini-*")
PYEOF
    echo
    echo "==> Step 5b/8: Seed each active home with its distinctive skill (skills/seed.md)"
    python3 scripts/seed_active_homes.py
    echo
else
    echo "==> Step 5/8: Skipped (--no-bootstrap)"
    echo
fi

# Step 5b: optional secure API key setup
if [ "$SETUP_KEYS" = "1" ]; then
    echo "==> Step 5b/8: Interactive secure API key setup"
    echo "    (Input hidden; values written with chmod 600.)"
    bash scripts/setup_api_keys.sh
    echo
fi

# Step 6: hermes_local adapter
if [ "$SKIP_ADAPTER_INSTALL" = "0" ]; then
    echo "==> Step 6/8: Register hermes_local adapter plugin"
    bash scripts/install_hermes_adapter_plugin.sh
    echo
else
    echo "==> Step 6/8: Skipped (--skip-adapter-install)"
    echo
fi

# Step 7: dreaming + cross-agent aggregator + observability crons
if [ "$SKIP_DREAMING" = "0" ] && [ "$SKIP_BOOTSTRAP" = "0" ]; then
    echo "==> Step 7/8: Install nightly Dreaming cron in every ~/.hermes-mini-<slug>/cron/"
    bash scripts/install_dreaming.sh
    echo
    echo "==> Step 7b/8: Install Winston cross-agent dream aggregator (V8.8)"
    bash scripts/install_dream_aggregator.sh
    echo
    echo "==> Step 7c/8: Install V8.9 observability crons (metrics, system outcomes, redundancy)"
    bash scripts/install_observability_crons.sh
    echo
else
    echo "==> Step 7/8: Skipped (--no-dreaming or --no-bootstrap)"
    echo
fi

# Step 8: Paperclip import (manual; mini doesn't ship the importer)
echo "==> Step 8/8: Manual Paperclip import"
echo "  Mini's V7 baseline does not bundle an automated Paperclip importer."
echo "  Use SoftwareHouse/paperclip/agents.json with paperclipai company import."
echo

echo "==================================================================="
echo " Install complete."
echo "==================================================================="
echo
echo " Artifacts:"
echo "   workspace/                            — local PRD/SDD/ticket tree"
echo "   ~/.hermes-mini-<slug>/                — 7 per-agent Hermes homes (Active Mini)"
echo "   ~/.hermes-mini-<slug>/cron/dream.cron — V8.6 nightly Dreaming"
echo "   ~/.hermes-mini-arthur/cron/*.cron     — V8.9 metrics/budget watchers"
echo "   ~/.paperclip/adapter-plugins.json     — hermes_local adapter"
echo
echo " Hard rules:"
echo "   - Context pack before non-trivial work."
echo "   - Architecture before tickets."
echo "   - Tests before code."
echo "   - Green + reviewed before merge."
echo "   - Human approval for governance/merge/deploy/trading changes."
echo
echo " Mini <-> Pantheon role map: SoftwareHouse/policies/mini_agent_role_map.yaml"
echo " Smoke ramp:                 SMOKE_SCALE.md (2 -> 7 agents)"
echo " Walkthrough:                examples/mini_weekly_intel_walkthrough.md"
